create database atm_db;
use atm_db;
CREATE TABLE Admin (
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(255) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE Customer (
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Aadhar CHAR(12) UNIQUE NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    Mobile CHAR(10) UNIQUE NOT NULL,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE Bank (
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Branch VARCHAR(255) NOT NULL,
    IFSC_Code VARCHAR(10) UNIQUE NOT NULL,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE ATM (
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    ATMBranch VARCHAR(255) NOT NULL,
    ATMCode VARCHAR(15) UNIQUE NOT NULL,
    Bank_Id BIGINT NOT NULL,
    Balance DECIMAL(15,2) DEFAULT 0,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (Bank_Id) REFERENCES Bank(Id) ON DELETE CASCADE
);
CREATE TABLE Card (
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    Customer_Id BIGINT NOT NULL,
    Card_No VARCHAR(19) UNIQUE NOT NULL,
    Pin CHAR(4) NOT NULL,
    Bank_Id BIGINT NOT NULL,
    Balance DECIMAL(15,2) DEFAULT 0,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (Customer_Id) REFERENCES Customer(Id) ON DELETE CASCADE,
    FOREIGN KEY (Bank_Id) REFERENCES Bank(Id) ON DELETE CASCADE
);
CREATE TABLE Transaction (
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    Balance DECIMAL(15,2) NOT NULL,
    TransactionType ENUM('CREDIT', 'DEBIT') NOT NULL,
    Card_No VARCHAR(20) NOT NULL,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (Card_No) REFERENCES Card(Card_No) ON DELETE CASCADE
);

insert into admin(Username, Password) value("root", "root");



